spring:
  application:
  name: transfers-realization-service
  profiles:
    active: production
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
#      properties: adding annotation spoils the app
      ##      spring.json.trusted.packages: * #"com.kodilla.commons"
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:
server:
  port: 9991